"""feature 004: monto y nota en membresias, permiso membership.renovar

Revision ID: 1d22a2198fbe
Revises: e57695beaef9
Create Date: 2026-07-10 15:57:20.161118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d22a2198fbe'
down_revision = 'e57695beaef9'
branch_labels = None
depends_on = None


permisos_table = sa.table(
    "permisos",
    sa.column("codigo", sa.String),
    sa.column("descripcion", sa.String),
)

_CATALOGO_NUEVO = [
    {
        "codigo": "membership.renovar",
        "descripcion": "Renovar la membresía de un socio (POST /usuarios/{id}/membresias/renovar).",
    },
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: autogenerate detectó como "removido" el índice único parcial
    # ix_checkins_usuario_dia_activo de 001 (creado con SQL crudo, Alembic no
    # lo reconoce como metadata ORM) y proponía un DROP INDEX — se quita a
    # mano, igual que en e8bdfb173fb7 (002) y e57695beaef9 (003); ese índice
    # sigue vigente.
    op.add_column('membresias', sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('membresias', sa.Column('nota', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
    op.bulk_insert(permisos_table, _CATALOGO_NUEVO)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membresias', 'nota')
    op.drop_column('membresias', 'monto')
    # ### end Alembic commands ###
    op.execute("DELETE FROM permisos WHERE codigo = 'membership.renovar'")
