"""init

Revision ID: faae8fa060f4
Revises: 
Create Date: 2026-07-08 05:11:35.258180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faae8fa060f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_membresia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('visitas_totales', sa.Integer(), nullable=False),
    sa.Column('cupo_invitados', sa.Integer(), nullable=False),
    sa.Column('duracion_dias', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_membresia_id'), 'tipos_membresia', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('rol', sa.Enum('invitado', 'miembro', 'empleado', 'administrador', name='rolusuario'), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estadousuario'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_cedula'), 'usuarios', ['cedula'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resultado', sa.Enum('exitoso', 'denegado', name='resultadocheckin'), nullable=False),
    sa.Column('razon_denegacion', sa.String(length=50), nullable=True),
    sa.Column('titular_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['titular_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_id'), 'checkins', ['id'], unique=False)
    op.create_index(op.f('ix_checkins_usuario_id'), 'checkins', ['usuario_id'], unique=False)
    op.create_table('invitados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('titular_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['titular_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitados_cedula'), 'invitados', ['cedula'], unique=False)
    op.create_index(op.f('ix_invitados_id'), 'invitados', ['id'], unique=False)
    op.create_table('membresias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('miembro_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('visitas_restantes', sa.Integer(), nullable=False),
    sa.Column('cupo_invitados_restantes', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'vencida', name='estadomembresia'), nullable=False),
    sa.ForeignKeyConstraint(['miembro_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_membresia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membresias_id'), 'membresias', ['id'], unique=False)
    op.create_index(op.f('ix_membresias_miembro_id'), 'membresias', ['miembro_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membresias_miembro_id'), table_name='membresias')
    op.drop_index(op.f('ix_membresias_id'), table_name='membresias')
    op.drop_table('membresias')
    op.drop_index(op.f('ix_invitados_id'), table_name='invitados')
    op.drop_index(op.f('ix_invitados_cedula'), table_name='invitados')
    op.drop_table('invitados')
    op.drop_index(op.f('ix_checkins_usuario_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cedula'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipos_membresia_id'), table_name='tipos_membresia')
    op.drop_table('tipos_membresia')
    # ### end Alembic commands ###
